# Basic Array Operations

In [1]:
import numpy as np

In [77]:
# Creating One-Dimensional Array

a = np.array([1,2,3])

# Access elements
print(a[0])
print(a[1])

# It also support negative indexing
print(a[-1])

1
2
3


In [92]:
# Creating Two-Dimensional Array

a = np.array([[1,2,3],[4,5,6]])

print(a,'\n')

# Access elements
print(a[0])
print(a[0][2],'\n')

# We can also access elements using [row,column]
print(a[1,1],'\n')

# Negative Indexing
print(a[-1],'\n')

[[1 2 3]
 [4 5 6]] 

[1 2 3]
3 

5 

[4 5 6] 



In [29]:
# ndim give the dimensions of the array
 
a = np.array([1,2,3])
b = np.array([[1,2,3],[4,5,6]])

print(a.ndim)
print(b.ndim)

1
2


In [30]:
# dtype give the Data-type of array

a = np.array([1,2,3])
b = np.array([1.3,2.4])

print(a.dtype)
print(b.dtype)

int32
float64


In [43]:
# We can also specify the data-type of array using dtype

a = np.array([1,2,3] ,dtype = np.float64)
print(a.dtype)
print(a,'\n')

b = np.array([1,2,3] ,dtype = complex)
print(b.dtype)
print(b)

float64
[1. 2. 3.] 

complex128
[1.+0.j 2.+0.j 3.+0.j]


In [31]:
# size give the number of elements in the array

a = np.array([1,2,3])
b = np.array([[1,2,3],[4,5,6]])

print(a.size)
print(b.size)

3
6


In [32]:
# itemsize give the byte-size of each element

a = np.array([1,2,3])       # Integer take 4-bytes
b = np.array([1.3,2.4])     # flost take 8-bytes


print(a.itemsize)
print(b.itemsize)  

4
8


In [37]:
# shape give the shape(rows and columns) of the array

a = np.array([1,2,3])
b = np.array([[1,2,3],[4,5,6]])

print(a,'\n')
print(b,'\n')

print(a.shape)
print(b.shape)


[1 2 3] 

[[1 2 3]
 [4 5 6]] 

(3,)
(2, 3)


In [45]:
# We can also initialize the array using the place-holder numbers

# we have to give shape as a argument

a = np.zeros((3,4))
print(a,'\n')

b = np.ones((3,4))
print(b)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]] 

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [48]:
# We can also create the array using the arange() function

a = np.arange(1,5)
print(a)

# we can also give the step size
b = np.arange(1,6,2)
print(b)

[1 2 3 4]
[1 3 5]


In [51]:
# linspace() is used to generate the numbers between two numbers that are linearly spaced

a = np.linspace(1,5,10)
print(a,'\n')

b = np.linspace(1,5,6)
print(b)

[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ] 

[1.  1.8 2.6 3.4 4.2 5. ]


In [59]:
# reshape() is used to reshape the shape(dimensions) of the array

a = np.array([[1,2],[3,4],[5,6]])

print(a.shape)
print(a,'\n')

a = a.reshape(2,3)
print(a.shape)
print(a)



(3, 2)
[[1 2]
 [3 4]
 [5 6]] 

(2, 3)
[[1 2 3]
 [4 5 6]]


In [65]:
# ravel() flaten the array make it one dimension

a = np.array([[1,2],[3,4],[5,6]])

print(a,'\n')

a = a.ravel()
print(a)

[[1 2]
 [3 4]
 [5 6]] 

[1 2 3 4 5 6]


In [66]:
# min() give the minimum element in the array

a = np.array([1,2,3,6,5,8])

print(a.min())

1


In [67]:
# max() give the maximum element in the array

a = np.array([1,2,3,6,5,8])

print(a.max())

8


In [68]:
# sum() sum all the numbers together

a = np.array([1,2,3,6,5,8])

print(a.sum())

25


In [71]:
# Axix are the rows and columns in the array
# Axis-0 is column
# Axis-1 is row

# We can also sum-up the elements on the axis

a = np.array([[1,2],[3,4],[5,6]])

print(a,'\n')
print(a.sum(axis=0),'\n')
print(a.sum(axis=1),'\n')

[[1 2]
 [3 4]
 [5 6]] 

[ 9 12] 

[ 3  7 11] 



In [72]:
# sqrt() find the square-root of all the elements in the array

a = np.array([1,2,3,6,5,8])

print(np.sqrt(a))

[1.         1.41421356 1.73205081 2.44948974 2.23606798 2.82842712]


In [73]:
# std() find the standard deviation

a = np.array([1,2,3,6,5,8])

print(np.std(a))

2.4094720491334933


# Indexing and Slicing

In [78]:
# Slicing -> accessing the range of elements from the array using the index-subrange [:]

a = np.array([1,2,3,6,5,8])

print(a[0:4])
print(a[0:5])


[1 2 3 6]
[1 2 3 6 5]


In [96]:
# Two-Dimensional Array

a = np.array([[1,2,3],[4,5,6],[7,8,9]])

print(a,'\n')

print(a[0:2],'\n')
print(a[1:3],'\n')

# We can also access specific multiple elements [-:-,-] first is rows-range second is column range
print(a[0:2,2],'\n')

print(a[0:3,0:2],'\n')

print(a[-1,0:2],'\n')

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

[[1 2 3]
 [4 5 6]] 

[[4 5 6]
 [7 8 9]] 

[3 6] 

[[1 2]
 [4 5]
 [7 8]] 

[7 8] 

