# Introduction

In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [2]:
# Numpy most useful feature is n-dimentional array object (a.k.a -> ndarray)

# Creating Numpy array

import numpy as np

a = np.array([1,2,3])

a

array([1, 2, 3])

In [4]:
# We can access the elements using indexes

a = np.array([1,2,3])

print(a[0])
print(a[1])

1
2


In [5]:
# Numpy Array is very similar to Python List But

# Three main benefits of Numpy Array over Python List:
# Less memory
# Fast
# Convinient 

In [6]:
# Comparing Numpy Array with Python List

# Less Memory

import numpy as np
import time
import sys

List = range(1000)
print(sys.getsizeof(5)*len(List))

array = np.arange(1000)
print(array.size*array.itemsize)

# In Numpy Array the values are stored in contiguous memory location and each value is of 4-byte (for integers).

# In Python everything is a object. List will contain a list of pointers first and each pointer will point to 
# another location in the memory which will our object and size of one object is 14-bytes

# That's why Numpy Array Memory consumption is very less as compared to Python List

28000
4000


In [8]:
# Fast

import numpy as np
import time

size = 1000000

l1 = range(size)
l2 = range(size)

a1 = np.arange(size)
a2 = np.arange(size)

# Python List
start = time.time()
result = [(x+y) for x,y in zip(l1,l2)] # zip() combine the two list together in a tuple
print("List took",(time.time()-start)*1000)

# Numpy Array
start = time.time()
result = a1 + a2
print("Array took",(time.time()-start)*1000)

List took 364.52770233154297
Array took 19.826889038085938


In [14]:
# Convinient

import numpy as np

a1 = np.array([1,2,3])
a2 = np.array([4,5,6]
              )
# Adding two Numpy Arrays
print(a1+a2)

# Subtracting two Arrays
print(a2-a1)

# Multiplication
print(a1*a2)

# Division
print(a1/a2)

# Dot Product
print(a1.dot(a2))

[5 7 9]
[3 3 3]
[ 4 10 18]
[0.25 0.4  0.5 ]
32
