# Iterate using nditer

In [1]:
import numpy as np

In [2]:
a = np.arange(12).reshape(3,4)
print(a,'\n')

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 



In [3]:
# Iterate through rows

a = np.arange(12).reshape(3,4)

for row in a:
    print(row)
    
# Print each element

for row in a:
    for cell in row:
        print(cell)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]
0
1
2
3
4
5
6
7
8
9
10
11


In [4]:
# Flaten the list and print every cell

a = np.arange(12).reshape(3,4)

for cell in a.flat:
    print(cell) 
    
print()

for cell in a.flatten():
    print(cell) 

0
1
2
3
4
5
6
7
8
9
10
11

0
1
2
3
4
5
6
7
8
9
10
11


In [5]:
# The more sophisticated way of iterating the array is using nditer() it has the same effect as flatten()

a = np.arange(12).reshape(3,4)

for x in np.nditer(a, order='C'): # C print in row-wise (C Order)
    print(x)

0
1
2
3
4
5
6
7
8
9
10
11


In [6]:
a = np.arange(12).reshape(3,4)

for x in np.nditer(a, order='F'): # F print in column-wise (Fortran Order)
    print(x)

0
4
8
1
5
9
2
6
10
3
7
11


In [7]:
# Printing entire column on each iteration

a = np.arange(12).reshape(3,4)

for x in np.nditer(a, order='F', flags=['external_loop']): 
    print(x)

[0 4 8]
[1 5 9]
[ 2  6 10]
[ 3  7 11]


In [8]:
# Modify array during iteration

a = np.arange(12).reshape(3,4)

for x in np.nditer(a, order='F', op_flags=['readwrite']): 
    x[...] = x*x # square of each number
    
print(a)

[[  0   1   4   9]
 [ 16  25  36  49]
 [ 64  81 100 121]]


In [11]:
# Iterate through two Numpy Arrays simultaneously

# For this the arrays should be broad-castable eiter there shape should be same or one of the dimensions in one of 
# the array should be One

a = np.arange(12).reshape(3,4)
b = np.arange(3,15,4).reshape(3,1)

print(a,'\n')
print(b,'\n')


for x,y in np.nditer([a,b]):
    print(x,y)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

[[ 3]
 [ 7]
 [11]] 

0 3
1 3
2 3
3 3
4 7
5 7
6 7
7 7
8 11
9 11
10 11
11 11


In [12]:
a = np.arange(12).reshape(3,4)
b = np.arange(3,15,4).reshape(4,1)

print(a,'\n')
print(b,'\n')


for x,y in np.nditer([a,b]):
    print(x,y)

ValueError: cannot reshape array of size 3 into shape (4,1)